type DummyType = {
  nameBook: string;
  writer: string;
  ratting: number;
  pages: number;
  star: number;
  riviews: string;
  amountRiviews: number;
  aboutBook: string;
  category: string;
  imgBook: string;
};

export const dummy: DummyType[] = [
  {
    nameBook: "The Silent Forest",
    writer: "Amelia Hart",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Sebuah perjalanan misteri di hutan sunyi.",
    category: "Novel",
    imgBook: "/src/assets/img1.jpg",
  },
  {
    nameBook: "Journey to the Stars",
    writer: "Michael Stone",
    ratting: 4.2,
    pages: 280,
    star: 4,
    riviews: "Ceritanya penuh imajinasi!",
    amountRiviews: 85,
    aboutBook: "Petualangan luar angkasa yang penuh kejutan.",
    category: "Sci-Fi",
    imgBook: "/src/assets/img1.jpg",
  },
  {
    nameBook: "Whispers of the Sea",
    writer: "Sofia Williams",
    ratting: 4.7,
    pages: 350,
    star: 5,
    riviews: "Sangat menyentuh hati.",
    amountRiviews: 200,
    aboutBook: "Kisah cinta dan kehilangan di tepi laut.",
    category: "Romance",
    imgBook: "/src/assets/img1.jpg",
  },
  {
    nameBook: "Shadows in the Alley",
    writer: "David Carter",
    ratting: 4.0,
    pages: 300,
    star: 4,
    riviews: "Seru dan penuh teka-teki.",
    amountRiviews: 90,
    aboutBook: "Kejahatan misterius di gang gelap kota.",
    category: "Thriller",
    imgBook: "/src/assets/img1.jpg",
  },
  {
    nameBook: "Beyond the Horizon",
    writer: "Hannah Lee",
    ratting: 4.3,
    pages: 310,
    star: 4,
    riviews: "Membuka wawasan baru.",
    amountRiviews: 110,
    aboutBook: "Perjalanan mencari arti kehidupan.",
    category: "Philosophy",
    imgBook: "/src/assets/img1.jpg",
  },
  {
    nameBook: "Garden of Memories",
    writer: "Ethan Walker",
    ratting: 4.6,
    pages: 290,
    star: 5,
    riviews: "Indah dan penuh makna.",
    amountRiviews: 150,
    aboutBook: "Kisah keluarga dan kenangan manis di taman kecil.",
    category: "Drama",
    imgBook: "/src/assets/img1.jpg",
  },
  {
    nameBook: "Echoes of Tomorrow",
    writer: "Isabella Moore",
    ratting: 4.8,
    pages: 360,
    star: 5,
    riviews: "Bikin merinding, keren banget!",
    amountRiviews: 210,
    aboutBook: "Waktu dan masa depan yang saling bertabrakan.",
    category: "Sci-Fi",
    imgBook: "/src/assets/img1.jpg",
  },
  {
    nameBook: "The Lost Kingdom",
    writer: "Oliver Johnson",
    ratting: 4.4,
    pages: 340,
    star: 4,
    riviews: "Fantasy dengan dunia baru yang menarik.",
    amountRiviews: 130,
    aboutBook: "Kerajaan hilang yang penuh misteri dan legenda.",
    category: "Fantasy",
    imgBook: "/src/assets/img2.jpg",
  },
  {
    nameBook: "Letters from Autumn",
    writer: "Grace Miller",
    ratting: 4.5,
    pages: 275,
    star: 5,
    riviews: "Romantis sekali, cocok buat malam tenang.",
    amountRiviews: 175,
    aboutBook: "Sepasang kekasih yang terpisahkan musim gugur.",
    category: "Romance",
    imgBook: "/src/assets/img2.jpg",
  },
  {
    nameBook: "Secrets of the Tower",
    writer: "James Parker",
    ratting: 4.1,
    pages: 330,
    star: 4,
    riviews: "Penuh misteri sampai akhir.",
    amountRiviews: 95,
    aboutBook: "Menjelajahi menara tua penuh rahasia.",
    category: "Mystery",
    imgBook: "/src/assets/img2.jpg",
  },
  {
    nameBook: "Winds of Freedom",
    writer: "Emily Brown",
    ratting: 4.6,
    pages: 310,
    star: 5,
    riviews: "Inspiratif banget!",
    amountRiviews: 160,
    aboutBook: "Kebebasan yang diperjuangkan lewat perjalanan panjang.",
    category: "Drama",
    imgBook: "/src/assets/img2.jpg",
  },
  {
    nameBook: "The Hidden Path",
    writer: "Alexander Scott",
    ratting: 4.3,
    pages: 295,
    star: 4,
    riviews: "Ceritanya bikin penasaran terus.",
    amountRiviews: 120,
    aboutBook: "Petualangan melalui jalan tersembunyi.",
    category: "Adventure",
    imgBook: "/src/assets/img2.jpg",
  },
  {
    nameBook: "Canvas of Dreams",
    writer: "Lily Adams",
    ratting: 4.9,
    pages: 370,
    star: 5,
    riviews: "Salah satu novel terbaik!",
    amountRiviews: 250,
    aboutBook: "Mimpi-mimpi yang dituangkan di atas kanvas kehidupan.",
    category: "Drama",
    imgBook: "/src/assets/img2.jpg",
  },
];
