type DummyType = {
  nameBook: string;
  writer: string;
  ratting: number;
  pages: number;
  star: number;
  riviews: string;
  amountRiviews: number;
  aboutBook: string;
  category: string;
  imgBook: string;
};

export const dummy: DummyType[] = [
  {
    nameBook: "Teruslah Bodoh Jangan Pintar",
    writer: "Tere Liye",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/src/assets/TeruslahBodohJanganPintar.jpg",
  },
  {
    nameBook: "Untukmu, Anak Bungsu",
    writer: "Hidya Hanin",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/src/assets/UntukmuAnakBungsu.jpg",
  },

  {
    nameBook: "Hidup Ini Terlalu Banyak Kamu",
    writer: "Pidi Baiq",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/path/to/image.jpg",
  },

  {
    nameBook: "Ternyata Tanpamu...",
    writer: "Natasha Rizky",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/path/to/image.jpg",
  },
  {
    nameBook: "Laut Bercerita",
    writer: "Leila S. Chudori",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/path/to/image.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/path/to/image.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/path/to/image.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/path/to/image.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/path/to/image.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/path/to/image.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/path/to/image.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/path/to/image.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/path/to/image.jpg",
  },
];
