type DummyType = {
  nameBook: string;
  writer: string;
  ratting: number;
  pages: number;
  star: number;
  riviews: string;
  amountRiviews: number;
  aboutBook: string;
  category: string;
  imgBook: string;
};

export const dummy: DummyType[] = [
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/src/assets/img1.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/src/assets/img1.jpg",
  },

  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/src/assets/img1.jpg",
  },

  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/src/assets/img1.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/src/assets/img1.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/src/assets/img1.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/src/assets/img1.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/src/assets/img2.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/src/assets/img2.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/src/assets/img2.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/src/assets/img2.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/src/assets/img2.jpg",
  },
  {
    nameBook: "Contoh Judul",
    writer: "Nama Penulis",
    ratting: 4.5,
    pages: 320,
    star: 5,
    riviews: "Buku yang sangat menarik!",
    amountRiviews: 120,
    aboutBook: "Deskripsi singkat tentang buku ini...",
    category: "Novel",
    imgBook: "/src/assets/img2.jpg",
  },
];
